baseURL = "https://retroblogz.netlify.app/"  # Ensure you include the protocol
title = "ريترو بلوغز"
theme = "zahi"
languageCode = "ar"
defaultContentLanguage = "ar"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "الرئيسية"
    name = "الرئيسية"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "المقالات"
    name = "المدونه"
    url = "/posts"
    weight = 10

[params]

[services]
  [services.disqus]
    shortname = "foobar"  # Update with your actual Disqus shortname


